# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.grievances.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('landmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Tracking codes must use the GRV-YYYY-NNNNNN format.', regex='^GRV-\\d{4}-\\d{6}$')])),
                ('raw_text', models.TextField(validators=[apps.grievances.models.validate_non_empty_text])),
                ('landmark_mention', models.CharField(blank=True, max_length=255)),
                ('citizen_location_text', models.TextField(blank=True)),
                ('image_attachment_metadata', models.JSONField(blank=True, default=dict, validators=[apps.grievances.models.validate_metadata_mapping])),
                ('normalized_summary', models.TextField(blank=True)),
                ('category_code', models.CharField(blank=True, db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Use a lowercase category code containing letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('landmark_resolution_metadata', models.JSONField(blank=True, default=dict, validators=[apps.grievances.models.validate_metadata_mapping])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('duplicate_detection_metadata', models.JSONField(blank=True, default=dict, validators=[apps.grievances.models.validate_metadata_mapping])),
                ('image_validation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.grievances.models.validate_metadata_mapping])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('enrichment_pending', 'Enrichment pending'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=32)),
                ('status_reason', models.TextField(blank=True)),
                ('status_metadata', models.JSONField(blank=True, default=dict, validators=[apps.grievances.models.validate_metadata_mapping])),
                ('submitted_at', models.DateTimeField()),
                ('last_status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='departments.department')),
                ('possible_duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='grievances.grievance')),
                ('resolved_landmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_grievances', to='landmarks.landmark')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'db_table': 'grievances_grievance',
                'ordering': ('-submitted_at', '-id'),
            },
        ),
    ]
