# Generated by Django 5.2.14 on 2026-05-22 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='wards.ward'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', 'submitted_at'], name='grievance_status_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['department', 'status'], name='grv_department_status_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['ward', 'status'], name='grievance_ward_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high', 'urgent', 'critical'])), name='grievance_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='grievance',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'enrichment_pending', 'triaged', 'assigned', 'in_progress', 'resolved', 'rejected', 'closed'])), name='grievance_status_valid'),
        ),
    ]
