# Generated by Django 5.2.14 on 2026-05-23 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_dept_categories_gin_idx'),
        ('grievances', '0002_initial'),
        ('landmarks', '0001_initial'),
        ('wards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['submitter', 'submitted_at'], name='grv_submitter_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['-submitted_at'], name='grv_submitted_at_desc_idx'),
        ),
    ]
