# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.slas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='SLA codes must use the SLA-YYYY-NNNNNN format.', regex='^SLA-\\d{4}-\\d{6}$')])),
                ('response_due_at', models.DateTimeField()),
                ('resolution_due_at', models.DateTimeField()),
                ('sla_status', models.CharField(choices=[('active', 'Active'), ('breached', 'Breached'), ('paused', 'Paused'), ('satisfied', 'Satisfied'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('is_breached', models.BooleanField(db_index=True, default=False)),
                ('breach_type', models.CharField(choices=[('none', 'None'), ('response', 'Response'), ('resolution', 'Resolution'), ('both', 'Both')], db_index=True, default='none', max_length=16)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('next_escalation_due_at', models.DateTimeField(blank=True, null=True)),
                ('breach_metadata', models.JSONField(blank=True, default=dict, validators=[apps.slas.models.validate_metadata_mapping])),
                ('escalation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.slas.models.validate_metadata_mapping])),
                ('policy_snapshot_metadata', models.JSONField(blank=True, default=dict, validators=[apps.slas.models.validate_metadata_mapping])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='grievances.grievance')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
                'db_table': 'slas_sla',
                'ordering': ('response_due_at', 'resolution_due_at'),
                'indexes': [models.Index(fields=['is_breached', 'breached_at'], name='sla_breached_at_idx'), models.Index(fields=['sla_status', 'response_due_at'], name='sla_status_response_idx'), models.Index(fields=['sla_status', 'resolution_due_at'], name='sla_status_resolution_idx'), models.Index(fields=['next_escalation_due_at'], name='sla_next_escalation_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sla_status__in', ['active', 'breached', 'paused', 'satisfied', 'cancelled'])), name='sla_status_valid'), models.CheckConstraint(condition=models.Q(('breach_type__in', ['none', 'response', 'resolution', 'both'])), name='sla_breach_type_valid')],
            },
        ),
    ]
