# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.attachments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Attachment codes must use the ATT-YYYY-NNNNNN format.', regex='^ATT-\\d{4}-\\d{6}$')])),
                ('storage_reference', models.CharField(db_index=True, max_length=512, validators=[apps.attachments.models.validate_non_empty_text])),
                ('original_filename', models.CharField(max_length=255, validators=[apps.attachments.models.validate_non_empty_text])),
                ('content_type', models.CharField(db_index=True, help_text='Image MIME type, such as image/jpeg or image/png.', max_length=127, validators=[apps.attachments.models.validate_image_content_type])),
                ('file_size_bytes', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hexadecimal content fingerprint.', max_length=64, validators=[django.core.validators.RegexValidator(message='Content hash must be a SHA-256 hexadecimal digest.', regex='^[a-fA-F0-9]{64}$')])),
                ('attachment_metadata', models.JSONField(blank=True, default=dict, validators=[apps.attachments.models.validate_metadata_mapping])),
                ('image_validation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.attachments.models.validate_metadata_mapping])),
                ('image_issue_classification_metadata', models.JSONField(blank=True, default=dict, validators=[apps.attachments.models.validate_metadata_mapping])),
                ('image_text_consistency_metadata', models.JSONField(blank=True, default=dict, validators=[apps.attachments.models.validate_metadata_mapping])),
                ('moderation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.attachments.models.validate_metadata_mapping])),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments_attachment',
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
    ]
