# Generated by Django 5.2.14 on 2026-05-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievances.grievance'),
        ),
    ]
