# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.wards.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use a lowercase ward code containing letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('translated_names', models.JSONField(blank=True, default=dict, validators=[apps.wards.models.validate_translated_names])),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('officer_assignment_metadata', models.JSONField(blank=True, default=dict, validators=[apps.wards.models.validate_metadata_mapping])),
                ('landmark_mapping_metadata', models.JSONField(blank=True, default=dict, validators=[apps.wards.models.validate_metadata_mapping])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'db_table': 'wards_ward',
                'ordering': ('name', 'code'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='wards_active_name_idx')],
            },
        ),
    ]
