# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.departments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use a lowercase department code containing letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('translated_names', models.JSONField(blank=True, default=dict, validators=[apps.departments.models.validate_translated_names])),
                ('handled_categories', models.JSONField(blank=True, default=list, help_text='List of grievance category codes handled by this department.', validators=[apps.departments.models.validate_category_codes])),
                ('is_active', models.BooleanField(default=True)),
                ('escalation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.departments.models.validate_metadata_mapping])),
                ('sla_metadata', models.JSONField(blank=True, default=dict, validators=[apps.departments.models.validate_metadata_mapping])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments_department',
                'ordering': ('name', 'code'),
                'indexes': [models.Index(fields=['is_active', 'name'], name='departments_active_name_idx')],
            },
        ),
    ]
