# Generated by Django 5.2.14 on 2026-05-23 15:30

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=django.contrib.postgres.indexes.GinIndex(fields=['handled_categories'], name='dept_categories_gin_idx'),
        ),
    ]
