# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.landmarks.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Use a lowercase landmark code containing letters, numbers, and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('primary_name', models.CharField(db_index=True, max_length=255)),
                ('aliases_en', models.JSONField(blank=True, default=list, validators=[apps.landmarks.models.validate_non_empty_string_list])),
                ('aliases_ml', models.JSONField(blank=True, default=list, validators=[apps.landmarks.models.validate_non_empty_string_list])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('landmark_type', models.CharField(choices=[('junction', 'Junction'), ('hospital', 'Hospital'), ('school', 'School'), ('government_office', 'Government office'), ('market', 'Market'), ('temple', 'Temple'), ('mosque', 'Mosque'), ('church', 'Church'), ('bus_stop', 'Bus stop'), ('railway_station', 'Railway station'), ('mall', 'Mall'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('normalized_search_tokens', models.JSONField(blank=True, default=list, help_text='Canonical tokens prepared for fuzzy and mixed-language lookup.', validators=[apps.landmarks.models.validate_non_empty_string_list])),
                ('fuzzy_lookup_metadata', models.JSONField(blank=True, default=dict, validators=[apps.landmarks.models.validate_metadata_mapping])),
                ('ward_mapping_metadata', models.JSONField(blank=True, default=dict, validators=[apps.landmarks.models.validate_metadata_mapping])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landmark',
                'verbose_name_plural': 'Landmarks',
                'db_table': 'landmarks_landmark',
                'ordering': ('primary_name', 'code'),
                'indexes': [models.Index(fields=['is_active', 'primary_name'], name='landmarks_active_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('landmark_type__in', ['junction', 'hospital', 'school', 'government_office', 'market', 'temple', 'mosque', 'church', 'bus_stop', 'railway_station', 'mall', 'other'])), name='landmarks_type_valid')],
            },
        ),
    ]
