# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.users.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('ward_officer', 'Ward officer'), ('department_officer', 'Department officer'), ('municipal_admin', 'Municipal admin'), ('super_admin', 'Super admin'), ('field_verifier', 'Field verifier'), ('system_operator', 'System operator')], db_index=True, default='citizen', max_length=32)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Optional contact number in E.164 format.', max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a phone number in E.164 format, such as +919876543210.', regex='^\\+[1-9]\\d{1,14}$')])),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam')], default='en', max_length=2)),
                ('additional_translations', models.JSONField(blank=True, default=dict, help_text='Additional translated user profile values keyed by language.', validators=[apps.users.models.validate_translation_mapping])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'indexes': [models.Index(fields=['role', 'is_active'], name='users_role_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['citizen', 'ward_officer', 'department_officer', 'municipal_admin', 'super_admin', 'field_verifier', 'system_operator'])), name='users_role_valid'), models.CheckConstraint(condition=models.Q(('preferred_language__in', ['en', 'ml'])), name='users_preferred_language_valid')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
