# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.audit.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Audit codes must use the AUD-YYYY-NNNNNN format.', regex='^AUD-\\d{4}-\\d{6}$')])),
                ('target_model', models.CharField(db_index=True, max_length=128, validators=[apps.audit.models.validate_non_empty_text])),
                ('target_object_id', models.CharField(db_index=True, max_length=64, validators=[apps.audit.models.validate_non_empty_text])),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('permission_denied', 'Permission denied'), ('status_change', 'Status change'), ('assignment', 'Assignment'), ('escalation', 'Escalation'), ('breach', 'Breach'), ('export', 'Export'), ('admin_action', 'Admin action'), ('system_event', 'System event')], db_index=True, max_length=32)),
                ('request_metadata', models.JSONField(blank=True, default=dict, validators=[apps.audit.models.validate_metadata_mapping])),
                ('change_metadata', models.JSONField(blank=True, default=dict, validators=[apps.audit.models.validate_metadata_mapping])),
                ('security_metadata', models.JSONField(blank=True, default=dict, validators=[apps.audit.models.validate_metadata_mapping])),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'db_table': 'audit_audit_log',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
