# Generated by Django 5.2.14 on 2026-05-22 05:51

import apps.workflows.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(blank=True, db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Workflow event codes must use the WFE-YYYY-NNNNNN format.', regex='^WFE-\\d{4}-\\d{6}$')])),
                ('transition_type', models.CharField(choices=[('status_change', 'Status change'), ('assignment', 'Assignment'), ('reassignment', 'Reassignment'), ('escalation', 'Escalation'), ('resolution', 'Resolution'), ('rejection', 'Rejection'), ('closure', 'Closure'), ('comment', 'Comment')], db_index=True, max_length=32)),
                ('previous_status', models.CharField(choices=[('submitted', 'Submitted'), ('enrichment_pending', 'Enrichment pending'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=32)),
                ('new_status', models.CharField(choices=[('submitted', 'Submitted'), ('enrichment_pending', 'Enrichment pending'), ('triaged', 'Triaged'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], max_length=32)),
                ('transition_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('assignment_metadata', models.JSONField(blank=True, default=dict, validators=[apps.workflows.models.validate_metadata_mapping])),
                ('escalation_metadata', models.JSONField(blank=True, default=dict, validators=[apps.workflows.models.validate_metadata_mapping])),
                ('sla_metadata', models.JSONField(blank=True, default=dict, validators=[apps.workflows.models.validate_metadata_mapping])),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_events_as_assignee', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='grievances.grievance')),
            ],
            options={
                'verbose_name': 'Workflow event',
                'verbose_name_plural': 'Workflow events',
                'db_table': 'workflows_workflow_event',
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['grievance', 'occurred_at'], name='wf_grievance_occurred_idx'), models.Index(fields=['grievance', 'new_status'], name='wf_grievance_status_idx'), models.Index(fields=['actor', 'occurred_at'], name='wf_actor_occurred_idx'), models.Index(fields=['assignee', 'occurred_at'], name='wf_assignee_occurred_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('transition_type__in', ['status_change', 'assignment', 'reassignment', 'escalation', 'resolution', 'rejection', 'closure', 'comment'])), name='wf_transition_type_valid'), models.CheckConstraint(condition=models.Q(('previous_status__in', ['submitted', 'enrichment_pending', 'triaged', 'assigned', 'in_progress', 'resolved', 'rejected', 'closed'])), name='wf_previous_status_valid'), models.CheckConstraint(condition=models.Q(('new_status__in', ['submitted', 'enrichment_pending', 'triaged', 'assigned', 'in_progress', 'resolved', 'rejected', 'closed'])), name='wf_new_status_valid')],
            },
        ),
    ]
