# Generated by Django 5.2.14 on 2026-05-25 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_grievance_grv_submitter_submitted_idx_and_more'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowevent',
            name='wf_transition_type_valid',
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='transition_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('assignment', 'Assignment'), ('reassignment', 'Reassignment'), ('escalation', 'Escalation'), ('resolution', 'Resolution'), ('rejection', 'Rejection'), ('closure', 'Closure'), ('comment', 'Comment'), ('return', 'Return to intake')], db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='workflowevent',
            constraint=models.CheckConstraint(condition=models.Q(('transition_type__in', ['status_change', 'assignment', 'reassignment', 'escalation', 'resolution', 'rejection', 'closure', 'comment', 'return'])), name='wf_transition_type_valid'),
        ),
    ]
